//  Header search
export const ACTIVATE_HEADER_SEARCH_FIELD = 'INVERT_HEADER_SEARCH_FIELD_STATE';
export const CHANGE_HEADER_SEARCH_FIELD = 'CHANGE_HEADER_SEARCH_FIELD';
export const RESET_HEADER_SEARCH_FIELD = 'RESET_HEADER_SEARCH_FIELD';

//  Catalog search
export const CHANGE_CATALOG_SEARCH_FIELD = 'CHANGE_CATALOG_SEARCH_FIELD';
export const RESET_CATALOG_SEARCH_FIELD = 'RESET_CATALOG_SEARCH_FIELD';

//  Categories
export const FETCH_CATEGORIES_REQUEST = 'FETCH_CATEGORIES_REQUEST';
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS';
export const FETCH_CATEGORIES_FILED = 'FETCH_CATEGORIES_FILED';
export const CHANGE_ACTIVE_CATEGORIES = 'CHANGE_ACTIVE_CATEGORIES';
export const RESET_ERROR_CATEGORIES = 'RESET_ERROR_CATEGORIES';
export const RESET_CATEGORIES = 'RESET_CATEGORIES';

//  Top-sales
export const FETCH_TOPSALES_REQUEST = 'FETCH_TOPSALES_REQUEST';
export const FETCH_TOPSALES_SUCCESS = 'FETCH_TOPSALES_SUCCESS';
export const FETCH_TOPSALES_FILED = 'FETCH_TOPSALES_FILED';
export const RESET_ERROR_TOPSALES = 'RESET_ERROR_TOPSALES';
export const RESET_TOPSALES = 'RESET_TOPSALES';

//  Catalog items
export const FETCH_CATALOG_ITEMS_REQUEST = 'FETCH_CATALOG_ITEMS_REQUEST';
export const FETCH_CATALOG_ITEMS_SUCCESS = 'FETCH_CATALOG_ITEMS_SUCCESS';
export const FETCH_CATALOG_ITEMS_FILED = 'FETCH_CATALOG_ITEMS_FILED';
export const SET_FILTER_CATALOG_ITEMS = 'SET_CATALOG_ITEMS_FILTER';
export const RESET_FILTER_CATALOG_ITEMS = 'RESET_FILTER_CATALOG_ITEMS';
export const RESET_ERROR_CATALOG_ITEMS = 'RESET_ERROR_CATALOG_ITEMS';
export const RESET_CATALOG_ITEMS = 'RESET_CATALOG_ITEMS';

//  Product
export const FETCH_PRODUCT_REQUEST = 'FETCH_PRODUCT_REQUEST';
export const FETCH_PRODUCT_SUCCESS = 'FETCH_PRODUCT_SUCCESS';
export const FETCH_PRODUCT_FILED = 'FETCH_PRODUCT_FILED';
export const RESET_ERROR_PRODUCT = 'RESET_ERROR_PRODUCT';
export const CHANGE_PRODUCT_ACTIVE_SIZE = 'CHANGE_PRODUCT_ACTIVE_SIZE';
export const RESET_ACTIVE_SIZE_PRODUCT = 'RESET_ACTIVE_SIZE_PRODUCT';
export const CHANGE_PRODUCT_COUNT = 'CHANGE_PRODUCT_COUNT';

//  Cart
export const RESTORE_CART_STATE = 'RESTORE_CART_STATE';
export const ADD_CART_ITEM = 'ADD_CART_ITEM';
export const REMOVE_CART_ITEM = 'REMOVE_CART_ITEM';
export const RESET_CART = 'RESET_CART';

//  Order
export const CHANGE_ORDER_FIELD = 'CHANGE_ORDER_FIELD';
export const POST_ORDER_REQUEST = 'POST_ORDER_REQUEST';
export const POST_ORDER_SUCCESS = 'POST_ORDER_SUCCESS';
export const POST_ORDER_FILED = 'POST_ORDER_FILED';
export const RESET_ERROR_ORDER = 'RESET_ERROR_ORDER';
export const RESET_ORDER_FORM = 'RESET_ORDER_FORM';
